[package]
name = "client"
version = "0.1.0"
authors = ["Fabian Vowie <crymaprivat@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
detour = "0.7.1"
winapi = { version = "0.3", features = ["libloaderapi", "memoryapi"] }
process-memory = "0.4.0"
cpp = "0.5"
fern = "0.6.0"
chrono = "0.4.19"
log = "0.4.11"
once_cell = "1.4.1"
winreg = "0.7.0"

[build-dependencies]
cpp_build = "0.5"
