[package]
name = "client"
version = "0.1.0"
authors = ["Fabian Vowie <crymaprivat@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
detour = "0.7.1"
winapi = { version = "0.3", features = ["libloaderapi", "memoryapi"] }
process-memory = "0.4.0"
cpp = "0.5"

[build-dependencies]
cpp_build = "0.5"
