[workspace]
members = [
    "client",
    "hook",
    "launcher",
    "native-converter",
    "server",
    "shared",
]

default-members = ["launcher"]

[patch.crates-io]
lexical-core = { git = "https://github.com/Alexhuszagh/rust-lexical", tag = "v0.7.6" }