[package]
name = "server"
version = "0.1.0"
authors = ["Fabian Vowie <crymaprivat@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
fern = "0.6.0"
log = "0.4.11"
once_cell = "1.5.2"
shared = { path = "../shared" }
