name: Rust

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Style Check
      run: cargo fmt -- --check
#    - name: Run tests
#      run: cargo test --verbose
